[project]
name = "trader-skeleton"
version = "0.1.0"
description = "Mean-reversion trading pipeline skeleton: raw -> features -> signals -> backtest"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["trader"]
