data:
  raw_paths: ["./data/raw/*.parquet"]   # uprav dle prostředí
  tz: "UTC"
  adjusted_prices: false

cache:
  base_ohlcv: "data_cache/base_ohlcv.parquet"
  events: "data_cache/events.parquet"

strategies:
  mr:
    universe: "universes/universe_main.json"
    params:
      z_entry: -2.0
      z_exit: -0.5
      rsi2_buy_lt: 5
      rsi2_sell_gt: 95
      hurst_max: 0.45
      atr_stop_k: 0.7
      time_stop: 5
    risk:
      risk_per_trade: 0.01
      max_concurrent: 6

  tf:
    universe: "universes/universe_main.json"
    params:
      adx_min: 25
      sma_fast: 50
      sma_slow: 200
      atr_trail_k: 2.0
    risk:
      risk_per_trade: 0.01

  etf:
    universe: "universes/universe_etf.json"
    params:
      momentum_lookback_m: [3, 6]
      top_n: 4
      vola_lookback_d: 20
      max_weight: 0.25
    risk:
      gross_leverage: 1.0

scheduler:
  run_all_after_close: true
